CREATE TABLE poll (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sex TEXT NOT NULL,
  city TEXT NOT NULL,   
  emotion TEXT NOT NULL,
  month TEXT NOT NULL,
  poll_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP    
);

